#!/bin/sh

# Convert the given YML format files in the current directory back to gff.
# Run from the work directory.
if [ "${NWNTOOLS}x" == "x" ] ; then
	NWNTOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	echo Environement variable NWNTOOLS unset using ${NWNTOOLS}
fi

if [ -f ${NWNTOOLS}/tool_cfg ] ; then
	source ${NWNTOOLS}/tool_cfg
else
	echo unable to find config file ${NWNTOOLS}/tool_cfg
fi

usage() {
    echo "Usage : yml2gff <filename>"
    exit 1 
}

if [ ! $# -eq 1 ] ; then
    usage    
fi


YMLFILES=$1
#echo ${YMLFILES}

for i in ${YMLFILES} ; do
    #echo $i
    j=`echo $i | sed 's/\(.*\)\..*/\1/'`
    echo ${NWNGFF} -i $i -l yaml -o $j -k gff
    RES=`${NWNGFF} -i $i -l yaml -o $j -k gff`
    if [ "$?" -ne 0 ] ; then
	echo ERROR: ${RES}
	exit 1
    fi
    #rm -f $i
done

